const test = require('node:test')
const assert = require('node:assert/strict')
const Student = require('../models/Student')
const Company = require('../models/Company')
const { DEMO_ASSESSMENTS, DEMO_CHALLENGE_STATES, DEMO_DAILY_PRACTICE, DEMO_NETWORK_PEOPLE, DEMO_NETWORK_STATE, DEMO_SKILL_ACTIVITY, DEMO_SKILL_GAP_REPORT, DEMO_SKILLS, DEMO_STREAK_DAYS, DEMO_SUBMISSIONS, DEMO_TRUST_PENALTIES, demoCompanyGigState, demoNetworkProfile, demoStudentGigState, demoTaskLibraryState, demoWorkspaceState } = require('../config/showcaseFixtures')
const { DEMO_READ_ONLY_MESSAGE, assertNotDemo, demoReadOnlyError, isProtectedDemoWrite } = require('../utils/demoProtection')

test('demo records are fixtures and account schemas never persist demo flags', () => {
  assert.equal(Student.schema.path('demoMode'), undefined)
  assert.equal(Company.schema.path('demoMode'), undefined)
  assert.equal(demoStudentGigState().browseGigs.every(item => item.demoData), true)
  assert.equal(demoStudentGigState().opportunities.length, 4)
  assert.equal(demoStudentGigState().opportunities.every(item => item.demoData), true)
  assert.equal(demoStudentGigState().appliedGigs.length, 1)
  assert.equal(demoStudentGigState().savedGigIds.length, 1)
  assert.equal(demoStudentGigState().browseGigs.length, 6)
  assert.equal(demoStudentGigState().opportunities.every(item => item.companyLogo?.startsWith('/demo-companies/')), true)
  const demoActiveGigs = demoStudentGigState().activeGigBase
  assert.equal(demoActiveGigs.length, 4)
  assert.equal(demoActiveGigs.every(item => item.demoWork && item.opportunityId?.startsWith('demo-work-opportunity-')), true)
  assert.equal(demoActiveGigs.every(item => item.demoTaskSubmission?.workspace), true)
  assert.equal(demoActiveGigs.filter(item => item.taskSubmissionStatus !== 'selected').every(item => item.demoTaskSubmission?.workBrief), true)
  assert.deepEqual(new Set(demoActiveGigs.map(item => item.taskSubmissionStatus)), new Set(['selected', 'needs_revision', 'work_started', 'delivered']))
  const demoCompletedGigs = demoStudentGigState().completedGigs
  assert.equal(demoCompletedGigs.every(item => item.demoWork && item.demoTaskSubmission?.status === 'completed'), true)
  const companyGigs = demoCompanyGigState().gigs
  assert.equal(companyGigs.length, 6)
  assert.equal(companyGigs.every(item => item.companyLogo?.startsWith('/demo-companies/')), true)
  assert.deepEqual(new Set(companyGigs.map(item => item.status)), new Set(['Hiring', 'Reviewing', 'In Progress', 'Closed']))
  assert.deepEqual(new Set(companyGigs.map(item => item.mode)), new Set(['Remote', 'Hybrid', 'On-site']))
  assert.deepEqual(new Set(companyGigs.map(item => item.type)), new Set(['Project GIG', 'Internship']))
  assert.equal(companyGigs.every(item => item.demoData), true)
  const companyTasks = demoTaskLibraryState().tasks
  assert.equal(companyTasks.length, 10)
  assert.deepEqual(new Set(companyTasks.map(item => item.type)), new Set(['live_project', 'code', 'mcq', 'written', 'mixed', 'design', 'data_analysis', 'case_study', 'research', 'presentation']))
  assert.equal(companyTasks.every(item => item.demoData && item.id.startsWith('demo-task-')), true)
  assert.deepEqual(new Set(DEMO_SUBMISSIONS.slice(2).map(item => item.status)), new Set(['submitted', 'reviewed', 'needs_revision', 'selected', 'rejected', 'work_started', 'delivered']))
  const workspaceProjects = demoWorkspaceState().projects
  assert.equal(workspaceProjects.length, 7)
  assert.deepEqual(new Set(workspaceProjects.map(item => item.status)), new Set(['Planning', 'In Progress', 'Review', 'Completed']))
  assert.equal(workspaceProjects.every(item => item.demoData && item.id.startsWith('demo-project-')), true)
  assert.equal(workspaceProjects.every(item => item.studentAvatar?.startsWith('/demo-network/')), true)
  assert.equal(workspaceProjects.filter(item => item.title === 'Retail Inventory Dashboard').length, 2)
  assert.equal(DEMO_NETWORK_PEOPLE.length, 3)
  assert.equal(DEMO_NETWORK_PEOPLE.every(item => item.demoData && item.id.startsWith('demo-')), true)
  assert.equal(DEMO_NETWORK_STATE.incomingRequests.length, 1)
  assert.equal(DEMO_NETWORK_STATE.outgoingRequests.length, 1)
  assert.equal(DEMO_NETWORK_STATE.connections.length, 1)
  assert.equal(DEMO_NETWORK_STATE.incomingRequests[0].profile.relationship.status, 'incoming_pending')
  assert.equal(DEMO_NETWORK_STATE.outgoingRequests[0].profile.relationship.status, 'outgoing_pending')
  assert.equal(DEMO_NETWORK_STATE.openTeamPosts.length >= 9, true)
  assert.equal(DEMO_NETWORK_STATE.openTeamPosts.some(item => item.joinStatus === 'pending' && item.requestSource === 'application'), true)
  assert.equal(DEMO_NETWORK_STATE.openTeamPosts.some(item => item.joinStatus === 'pending' && item.requestSource === 'invitation'), true)
  assert.equal(DEMO_NETWORK_STATE.openTeamPosts.some(item => item.joinStatus === 'accepted'), true)
  assert.equal(DEMO_NETWORK_STATE.myTeamPosts[0].requests.some(item => item.status === 'pending' && item.source === 'application'), true)
  const demoProfile = demoNetworkProfile(DEMO_NETWORK_PEOPLE[0])
  assert.equal(demoProfile.avatar.startsWith('/demo-network/'), true)
  assert.equal(demoProfile.skills.every(item => item.verified && item.stage), true)
  assert.equal(demoProfile.activityDays.length > 0 && demoProfile.projects.length > 0, true)
  assert.equal(demoProfile.collaborationFocus.length > 0 && demoProfile.highlights.length > 0, true)
  assert.equal(demoProfile.contactVisible, false)
  assert.deepEqual(demoProfile.contactInfo, [])
  assert.equal(demoProfile.githubLink.length > 1 && Boolean(demoProfile.projects[0].demoLink), true)
  assert.equal(demoProfile.githubLink.every(item => item.saved && item.icon), true)
  assert.equal(demoProfile.contactInfo.every(item => item.saved), true)
  assert.equal(demoProfile.projects.every(item => item.saved), true)
  const connectedDemoProfile = demoNetworkProfile(DEMO_NETWORK_STATE.connections[0])
  assert.equal(connectedDemoProfile.contactVisible, true)
  assert.equal(connectedDemoProfile.contactInfo.length > 0 && connectedDemoProfile.contactInfo.every(item => item.saved), true)
})

test('only writes targeting fixture identifiers are blocked', () => {
  assert.equal(isProtectedDemoWrite({ method: 'GET', pathname: '/api/student/gigs/990001' }), false)
  assert.equal(isProtectedDemoWrite({ method: 'POST', pathname: '/api/student/gigs/990001/apply' }), true)
  assert.equal(isProtectedDemoWrite({ method: 'POST', pathname: '/api/student/gigs/990005/apply' }), true)
  assert.equal(isProtectedDemoWrite({ method: 'POST', pathname: '/api/student/opportunities/demo-opportunity-1/accept' }), true)
  assert.equal(isProtectedDemoWrite({ method: 'POST', pathname: '/api/student/opportunities/demo-opportunity-2/accept' }), true)
  assert.equal(isProtectedDemoWrite({ method: 'POST', pathname: '/api/student/network/connections/demo-student-3' }), true)
  assert.equal(isProtectedDemoWrite({ method: 'POST', pathname: '/api/student/network/connections/demo-connection-incoming-1/decision' }), true)
  assert.equal(isProtectedDemoWrite({ method: 'POST', pathname: '/api/student/network/team-ups/demo-team-1/join' }), true)
  assert.equal(isProtectedDemoWrite({ method: 'DELETE', pathname: '/api/company/workspace/projects/demo-project-1' }), true)
  assert.equal(isProtectedDemoWrite({ method: 'PATCH', pathname: '/api/student/profile' }), false)
  assert.equal(isProtectedDemoWrite({ method: 'POST', pathname: '/api/company/gigs' }), false)
})

test('demo record errors use the user-facing read-only message', () => {
  const error = demoReadOnlyError()
  assert.equal(error.statusCode, 403)
  assert.equal(error.message, DEMO_READ_ONLY_MESSAGE)
  assert.throws(() => assertNotDemo('demo-task-1'), { message: DEMO_READ_ONLY_MESSAGE })
})

test('static review fixtures are visibly protected', () => {
  assert.equal(DEMO_ASSESSMENTS.length, 6)
  assert.equal(DEMO_ASSESSMENTS.every(item => item.demoData && item.id.startsWith('demo-')), true)
  assert.deepEqual(new Set(DEMO_ASSESSMENTS.map(item => item.status)), new Set(['pending', 'needs_revision', 'approved', 'rejected']))
  assert.equal(DEMO_ASSESSMENTS.some(item => item.skillName === 'SQL' && item.mode === 'reverify' && item.status === 'needs_revision'), true)
  assert.equal(DEMO_ASSESSMENTS.some(item => item.skillName === 'Python' && item.mode === 'reverify' && item.status === 'rejected'), true)
  assert.equal(DEMO_TRUST_PENALTIES.length, 1)
  assert.equal(DEMO_TRUST_PENALTIES[0].demoData, true)
  assert.equal(DEMO_SKILLS.length, 6)
  assert.deepEqual(new Set(DEMO_SKILLS.map(item => item.renewalStatus)), new Set(['valid', 'due', 'unverified', 'expired', 'archived']))
  assert.equal(DEMO_SKILL_ACTIVITY.every(item => item.demoData && item.id.startsWith('demo-')), true)
  assert.equal(DEMO_DAILY_PRACTICE.every(item => item.demoData), true)
  assert.equal(DEMO_CHALLENGE_STATES.every(item => item.demoData), true)
  assert.equal(DEMO_STREAK_DAYS.every(item => item.demoData && item.days.length > 0), true)
  assert.equal(DEMO_SKILL_GAP_REPORT.demoData, true)
  assert.equal(DEMO_SKILL_GAP_REPORT.strengths.some(item => item.skill === 'React'), true)
})
